spring:
  application:
    name: ai-code
  profiles:
    active: local


langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: your-api-key
      embedding-model:
        model-name: text-embedding-v4
        api-key: your-api-key
      streaming-chat-model:
        model-name: qwen-max
        api-key: your-api-key
bigmodel:
  api-key: your-api-key
